name       : mate-user-admin
version    : 1.6.0
release    : 4
source     :
    - https://github.com/zhuyaliang/user-admin/archive/refs/tags/1.6.0.tar.gz : 305f2ea548c2eca4af741ee8cfeaa5ded7dac3b29f9a731f884abad00b7600c5
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : Users & groups management tool for the MATE desktop environment
description: |
    Users & groups management tool for the MATE desktop environment.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(group-service)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(pwquality)
setup      : |
    # Set our own defaults
    cp $pkgfiles/nuconfig data/mate-user-admin/

    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
