name       : mate-user-admin
version    : 1.6.0
release    : 5
source     :
    - git|https://github.com/zhuyaliang/user-admin : fe00805194e9bd7649c98ba4b02aa7c3deb23785
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : Users & groups management tool for the MATE desktop environment
description: |
    Users & groups management tool for the MATE desktop environment.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(group-service)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(pwquality)
setup      : |
    # Set our own defaults
    cp $pkgfiles/nuconfig data/mate-user-admin/

    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
