name       : mate-user-admin
version    : 1.6.0
release    : 6
source     :
    - git|https://github.com/zhuyaliang/user-admin : 4eb966b2cd9dd0f42a1fb9086eecbbc95b79a8b0
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : Users & groups management tool for the MATE desktop environment
description: |
    Users & groups management tool for the MATE desktop environment.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(group-service)
    - pkgconfig(libcrypt)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(pwquality)
setup      : |
    # Set our own defaults
    cp $pkgfiles/nuconfig data/mate-user-admin/

    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
