name       : mate-user-admin
version    : 1.5.2
release    : 1
source     :
    - https://github.com/zhuyaliang/user-admin/archive/1.5.2.tar.gz : fac5b24d49f3830fcda2ebb9b60debe0690ce19b61f9198dc13547c2f0b7aa3b
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : Users & groups management tool for the MATE desktop environment
description: |
    Users & groups management tool for the MATE desktop environment.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(group-service)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(pwquality)
setup      : |
    # Set our own defaults
    cp $pkgfiles/nuconfig data/mate-user-admin/

    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
